server.port=${PORT:8080}

# CognoDB Graph Connection Details
cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME}
cognodb.password=${COGNODB_PASSWORD}

# Automatically seed data on startup
app.seed.on-startup=true
