server.port=8080

# CognoDB Graph Connection Details
cognodb.uri=bolt+s://db-42acf968.databases.cognodb.com
cognodb.username=cognodb
cognodb.password=a342b03396556430aabb2faad351b2f9

# Automatically seed data on startup (true/false)
app.seed.on-startup=true
